
    const products =  [
        {
            "category": "clothes",
            "subcategory": "T-shirts",
            "name": "Fantasy T-shirt",
            "rating": 4,
            "image": "https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg",
            "description": "You won't like until you try it",
            "available": "yes",
            "condition": "new",
            "color": "blue",
            "price": 549,
            "discount": 0
        },
        {
            "category": "clothes",
            "subcategory": "shirts",
            "name": "Fantasy T-shirt",
            "rating": 4.5,
            "image": "https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/13.jpg",
            "description": "You won't like until you try it",
            "available": "yes",
            "condition": "new",
            "color": "red",
            "price": 499,
            "discount": 10
        },
        {
            "category": "clothes",
            "subcategory": "shirts",
            "name": "Fantasy shirt",
            "rating": 4.5,
            "image": "https://m.media-amazon.com/images/I/61ok3JpsF8L._AC_UL640_QL65_.jpg",
            "description": "You won't like until you try it",
            "available": "yes",
            "condition": "new",
            "color": "yellow",
            "price": 699,
            "discount": 50
        },
        {
            "category": "clothes",
            "subcategory": "T-shirts",
            "name": "Fantasy T-shirt",
            "rating": 4.3,
            "image": "https://m.media-amazon.com/images/I/71nBZ8ZOFRL._AC_UL640_FMwebp_QL65_.jpg",
            "description": "You won't like until you try it",
            "available": "yes",
            "condition": "new",
            "color": "grey",
            "price": 499,
            "discount": 10
        },
        {
            "category": "clothes",
            "subcategory": "jackets",
            "name": "Denim Jacket",
            "rating": 5,
            "image": "https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/15.jpg",
            "description": "You won't like until you try it",
            "available": "yes",
            "condition": "new",
            "color": "grey",
            "price": 2199,
            "discount": 10
        },
        {
            "category": "clothes",
            "subcategory": "jeans",
            "name": "slim fit jeans",
            "rating": 3.9,
            "image": "https://m.media-amazon.com/images/I/815pNx1Ns5L._AC_UL640_FMwebp_QL65_.jpg",
            "description": "You won't like until you try it",
            "available": "yes",
            "condition": "renewed",
            "color": "blue",
            "price": 1199,
            "discount": 5
        },
        {
            "category": "clothes",
            "subcategory": "jeans",
            "name": "Boyfriend jeans",
            "rating": 4,
            "image": "https://m.media-amazon.com/images/I/61QEJwzNtXS._AC_UL640_FMwebp_QL65_.jpg",
            "description": "You won't like until you try it",
            "available": false,
            "condition": "used",
            "color": "black",
            "price": 949,
            "discount": 5
        },
        {
            "category": "clothes",
            "subcategory": "shirts",
            "name": "sweatshirt",
            "rating": 3.2,
            "image": "https://m.media-amazon.com/images/I/71niKQBSoDL._AC_UL640_FMwebp_QL65_.jpg",
            "description": "You won't like until you try it",
            "available": true,
            "condition": "collectible",
            "color": "white",
            "price": 749,
            "discount": 5
        },
        {
            "category": "clothes",
            "subcategory": "shirts",
            "name": "Longsleeve",
            "rating": 4.1,
            "image": "https://m.media-amazon.com/images/I/61qcnAHZP3L._AC_UL640_FMwebp_QL65_.jpg",
            "description": "You won't like until you try it",
            "available": true,
            "condition": "collectible",
            "color": "black",
            "price": 1199,
            "discount": 0
        },
        {
            "category": "clothes",
            "subcategory": "shirts",
            "name": "Stripped sweatshirt",
            "rating": 4.4,
            "image": "https://m.media-amazon.com/images/I/61QSo+36ggS._AC_UL640_FMwebp_QL65_.jpg",
            "description": "You won't like until you try it",
            "available": true,
            "condition": "new",
            "color": "white",
            "price": 699,
            "discount": 10
        },
        {
            "category": "clothes",
            "subcategory": "trousers",
            "name": "Red chinos",
            "rating": 4.8,
            "image": "https://m.media-amazon.com/images/I/31GMNxnGlHL._AC_UL640_FMwebp_QL65_.jpg",
            "description": "You won't like until you try it",
            "available": true,
            "condition": "new",
            "color": "red",
            "price": 1999,
            "discount": 100
        },
        {
            "category": "clothes",
            "subcategory": "coats",
            "name": "Camel coat",
            "rating": 4,
            "image": "https://m.media-amazon.com/images/I/91CgDryObOL._AC_UL640_FMwebp_QL65_.jpg",
            "description": "You won't like until you try it",
            "available": true,
            "condition": "used",
            "color": "brown",
            "price": 1599,
            "discount": 99
        },
        {
            "category": "clothes",
            "subcategory": "jeans",
            "name": "Blue jeans",
            "rating": 5,
            "image": "https://m.media-amazon.com/images/I/41+3UgTBW3L._AC_UL640_FMwebp_QL65_.jpg",
            "description": "You won't like until you try it",
            "available": true,
            "condition": "new",
            "color": "blue",
            "price": 849,
            "discount": 0
        },
        {
            "category": "clothes",
            "subcategory": "T-shirts",
            "name": "Orange T-shirt",
            "rating": 4.7,
            "image": "https://m.media-amazon.com/images/I/71CW2w7qoBL._AC_UL640_FMwebp_QL65_.jpg",
            "description": "You won't like until you try it",
            "available": true,
            "condition": "new",
            "color": "orange",
            "price": 900,
            "discount": 0
        },
        {
            "category": "clothes",
            "subcategory": "skirts",
            "name": "Ballerina skirt",
            "rating": 4.6,
            "image": "https://m.media-amazon.com/images/I/61LW0LjM+yL._AC_UL640_FMwebp_QL65_.jpg",
            "description": "You won't like until you try it",
            "available": true,
            "condition": "collectible",
            "color": "white",
            "price": 700,
            "discount": 0
        }
    ]
    
    module.exports= {products};

